/**
 * Generates src/lib/poker/preflop-table.generated.ts
 * Computes all 169 canonical starting-hand equities vs one uniform random
 * opponent via Monte Carlo, then assigns 20 percentile buckets.
 */
import { makeDeck, seededRng, cardRank } from '../src/lib/poker/cards';
import { evaluate } from '../src/lib/poker/evaluator';

const SIMS = 4000;
const N_BUCKETS = 20;

function canonicalIndex(hole: number[]): { idx: number; label: string } {
  const r1 = Math.max(cardRank(hole[0]), cardRank(hole[1]));
  const r2 = Math.min(cardRank(hole[0]), cardRank(hole[1]));
  const suited = (hole[0] & 3) === (hole[1] & 3);
  const R = '23456789TJQKA';
  let idx: number;
  let label: string;
  if (r1 === r2) {
    idx = r1;
    label = `${R[r1]}${R[r1]}`;
  } else {
    const pair = (r1 * (r1 - 1)) / 2 + r2;
    idx = suited ? 13 + pair : 13 + 78 + pair;
    label = `${R[r1]}${R[r2]}${suited ? 's' : 'o'}`;
  }
  return { idx, label };
}

// Build one representative hole per canonical class
const holes: number[][] = new Array(169);
const labels: string[] = new Array(169);
for (let c1 = 0; c1 < 52; c1++) {
  for (let c2 = c1 + 1; c2 < 52; c2++) {
    const { idx, label } = canonicalIndex([c1, c2]);
    if (!holes[idx]) {
      holes[idx] = [c1, c2];
      labels[idx] = label;
    }
  }
}

const rng = seededRng(20260914);
const equities = new Array<number>(169).fill(0);

for (let i = 0; i < 169; i++) {
  const [a, b] = holes[i];
  let win = 0;
  for (let sim = 0; sim < SIMS; sim++) {
    const deck = makeDeck().filter((c) => c !== a && c !== b);
    // shuffle partial
    for (let k = deck.length - 1; k > 0; k--) {
      const j = Math.floor(rng() * (k + 1));
      [deck[k], deck[j]] = [deck[j], deck[k]];
    }
    const opp = [deck[0], deck[1]];
    const board = deck.slice(2, 7);
    const myScore = evaluate([a, b, ...board]);
    const oppScore = evaluate([opp[0], opp[1], ...board]);
    if (myScore > oppScore) win += 1;
    else if (myScore === oppScore) win += 0.5;
  }
  equities[i] = win / SIMS;
}

// Rank-based bucketing into N_BUCKETS
const order = equities.map((e, i) => ({ e, i })).sort((x, y) => x.e - y.e);
const buckets = new Array<number>(169).fill(0);
order.forEach((o, rank) => {
  buckets[o.i] = Math.min(N_BUCKETS - 1, Math.floor((rank / 169) * N_BUCKETS));
});

// Compute bucket average equity (useful for display)
const bucketEquity: number[] = new Array(N_BUCKETS).fill(0);
const bucketCount: number[] = new Array(N_BUCKETS).fill(0);
for (let i = 0; i < 169; i++) {
  bucketEquity[buckets[i]] += equities[i];
  bucketCount[buckets[i]]++;
}
for (let k = 0; k < N_BUCKETS; k++) bucketEquity[k] = bucketCount[k] ? bucketEquity[k] / bucketCount[k] : 0;

const out = `// AUTO-GENERATED by scripts/gen-preflop.ts — do not edit by hand.
// Preflop equity vs one uniform random opponent (Monte Carlo, ${SIMS} sims/hand)
// and 20 percentile buckets over the 169 canonical starting hands.

export const PREFLOP_EQUITY: number[] = [${equities.map((e) => e.toFixed(4)).join(', ')}];

export const PREFLOP_BUCKET: number[] = [${buckets.join(', ')}];

export const PREFLOP_LABELS: string[] = [${labels.map((l) => `'${l}'`).join(', ')}];

export const BUCKET_AVG_EQUITY: number[] = [${bucketEquity.map((e) => e.toFixed(4)).join(', ')}];
`;

await Bun.write('src/lib/poker/preflop-table.generated.ts', out);
console.log('AA equity:', equities[12].toFixed(3), '72o equity:', equities[13 + 78 + 1].toFixed(3));
console.log('buckets sizes:', bucketCount.join(','));
console.log('Wrote src/lib/poker/preflop-table.generated.ts');
